name: Maintenance Toggle
on:
  workflow_dispatch:
    inputs:
      enable:
        description: 'Enable maintenance mode?'
        type: boolean
        required: true

permissions:
  contents: write

jobs:
  toggle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git history

      - name: Toggle Mode
        id: toggle
        run: |
          if ${{ inputs.enable }}; then
            echo "ENABLING maintenance"
            if cmp -s maintenance.html index.html; then
              echo "Maintenance mode already active"
              echo "skip_commit=true" >> $GITHUB_OUTPUT
            else
              cp maintenance.html index.html
            fi
          else
            echo "DISABLING maintenance"
            if git diff --quiet HEAD -- index.html; then
              echo "Normal mode already active"
              echo "skip_commit=true" >> $GITHUB_OUTPUT
            else
              git checkout HEAD -- index.html
            fi
          fi

      - name: Commit Changes
        if: steps.toggle.outputs.skip_commit != 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Maintenance ${{ inputs.enable && 'ENABLED' || 'DISABLED' }} [skip ci]"
          git push
