name: Maintenance Toggle
on:
  workflow_dispatch:
    inputs:
      enable_maintenance:
        description: 'Enable maintenance mode?'
        required: true
        type: boolean
jobs:
  toggle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          if ${{ inputs.enable_maintenance }}; then
            mv maintenance.html index.html
          else
            git restore index.html
          fi
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Maintenance ${{ inputs.enable_maintenance && 'enabled' || 'disabled' }}"
          git push
